import { mkdtemp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { NestFactory } from '@nestjs/core';
import { GraphQLSchemaHost } from '@nestjs/graphql';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';
import { lexicographicSortSchema, printSchema } from 'graphql';

const REPO_ROOT = resolve(__dirname, '../../..');
const CONTRACT_DIR = resolve(REPO_ROOT, 'docs/api');

async function main(): Promise<void> {
  ensureContractEnv();
  const check = process.argv.includes('--check');
  const outDir = check
    ? await mkdtemp(join(tmpdir(), 'acres-contracts-'))
    : CONTRACT_DIR;
  try {
    await mkdir(outDir, { recursive: true });
    await writeContracts(outDir);
    if (check) await assertNoDrift(outDir);
  } finally {
    if (check) await rm(outDir, { recursive: true, force: true });
  }
}

async function writeContracts(outDir: string): Promise<void> {
  const [{ AppModule }, { configureApp }] = await Promise.all([
    import('../app.module.js'),
    import('../app.setup.js'),
  ]);
  const app = await NestFactory.create(AppModule, {
    bodyParser: false,
    logger: false,
  });
  configureApp(app);
  await app.init();
  try {
    const openapi = SwaggerModule.createDocument(
      app,
      new DocumentBuilder()
        .setTitle('Acres API')
        .setDescription('Versioned Acres REST API.')
        .setVersion('1.0.0')
        .addCookieAuth('acres_session', { type: 'apiKey', in: 'cookie' })
        .addApiKey(
          { type: 'apiKey', in: 'header', name: 'x-csrf-token' },
          'csrf',
        )
        .addApiKey(
          { type: 'apiKey', in: 'header', name: 'Idempotency-Key' },
          'idempotency',
        )
        .build(),
    );
    delete openapi.servers;
    await writeFile(
      join(outDir, 'openapi.json'),
      `${stableStringify(openapi)}\n`,
      'utf8',
    );

    const schema = app.get(GraphQLSchemaHost).schema;
    await writeFile(
      join(outDir, 'schema.graphql'),
      `${printSchema(lexicographicSortSchema(schema))}\n`,
      'utf8',
    );
    await writeFile(join(outDir, 'contracts.md'), contractsMarkdown(), 'utf8');
  } finally {
    await app.close();
  }
}

function ensureContractEnv(): void {
  const defaults: Record<string, string> = {
    NODE_ENV: 'test',
    PORT: '3999',
    CLIENT_ORIGIN: 'http://localhost:3000',
    DATABASE_URL:
      'postgresql://acres_test:acres_test_dev_password@localhost:5432/acres_test?schema=public',
    SESSION_COOKIE_NAME: 'acres_session',
    SESSION_TTL_DAYS: '30',
    SESSION_SECRET: 'contract-secret-that-is-at-least-32-characters',
    CSRF_COOKIE_NAME: 'acres_csrf',
    SCHEDULER_ENABLED: 'false',
    RATE_LIMIT_TTL_MS: '60000',
    RATE_LIMIT_DEFAULT_LIMIT: '1000',
    RATE_LIMIT_STRICT_LIMIT: '1000',
    TENANCY_ENABLED: 'true',
    INVITATION_TTL_HOURS: '24',
    ACCOUNT_TOKEN_TTL_MINUTES: '30',
    GRAPHQL_MAX_BYTES: '12000',
    GRAPHQL_MAX_DEPTH: '8',
    GRAPHQL_MAX_ALIASES: '12',
    GRAPHQL_MAX_COST: '250',
    GRAPHQL_MAX_FIRST: '50',
    GRAPHQL_MAX_NODES: '250',
    GRAPHQL_TIMEOUT_MS: '5000',
    IDEMPOTENCY_TTL_HOURS: '24',
  };
  for (const [key, value] of Object.entries(defaults)) {
    process.env[key] ??= value;
  }
}

async function assertNoDrift(tempDir: string): Promise<void> {
  const files = ['openapi.json', 'schema.graphql', 'contracts.md'];
  const drifted: string[] = [];
  for (const file of files) {
    const expected = await readFile(join(CONTRACT_DIR, file), 'utf8');
    const actual = await readFile(join(tempDir, file), 'utf8');
    if (expected !== actual) drifted.push(file);
  }
  if (drifted.length > 0) {
    throw new Error(`Contract drift detected: ${drifted.join(', ')}`);
  }
}

function stableStringify(value: unknown): string {
  return JSON.stringify(sortValue(value), null, 2);
}

function sortValue(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(sortValue);
  if (value && typeof value === 'object') {
    return Object.fromEntries(
      Object.entries(value as Record<string, unknown>)
        .filter(([, inner]) => inner !== undefined)
        .sort(([a], [b]) => a.localeCompare(b))
        .map(([key, inner]) => [key, sortValue(inner)]),
    );
  }
  return value;
}

function contractsMarkdown(): string {
  return `# Acres API contracts

Generated by \`npm run contracts:generate\`. Keep this matrix aligned with
\`openapi.json\` and \`schema.graphql\`; CI runs \`contracts:check\`.

## REST

| method | canonical path | auth | notes |
| --- | --- | --- | --- |
| GET | /health | public | version-neutral liveness |
| GET | /health/ready | public | version-neutral readiness |
| GET | /api/v1/auth/csrf | public | CSRF token issue route |
| POST | /api/v1/auth/register | public + CSRF | creates account/session |
| POST | /api/v1/auth/login | public + CSRF | creates session |
| POST | /api/v1/auth/logout | session + CSRF | revokes session |
| GET | /api/v1/auth/session | optional session | anonymous or active session |
| GET | /api/v1/account | session | safe account profile |
| GET | /api/v1/regions | public | global region list |
| GET | /api/v1/regions/:slug | public | one global region |
| POST | /api/v1/forms/contact | public + CSRF | public contact form |
| GET | /api/v1/jobs/runs | session | recent scheduled jobs |
| GET | /api/v1/organizations | session | account organizations |
| POST | /api/v1/organizations | session + CSRF + Idempotency-Key | create organization |
| GET | /api/v1/organizations/:organizationId | session + organization.read | selected organization |
| PATCH | /api/v1/organizations/:organizationId | session + CSRF + organization.update | rename organization |
| GET | /api/v1/organizations/:organizationId/members | session + members.read | member list |
| PATCH | /api/v1/organizations/:organizationId/members/:membershipId | session + CSRF + members.change_role | change role |
| DELETE | /api/v1/organizations/:organizationId/members/:membershipId | session + CSRF + members.revoke | revoke member |
| POST | /api/v1/organizations/:organizationId/ownership-transfers | session + CSRF + ownership.transfer + Idempotency-Key | transfer ownership |
| GET | /api/v1/organizations/:organizationId/invitations | session + invitations.read | invitation metadata |
| POST | /api/v1/organizations/:organizationId/invitations | session + CSRF + members.invite + Idempotency-Key | issue invitation |
| DELETE | /api/v1/organizations/:organizationId/invitations/:invitationId | session + CSRF + invitations.revoke | revoke invitation |
| POST | /api/v1/invitations/accept | session + CSRF + Idempotency-Key | accept invitation |

Old unversioned product paths are removed in Phase 4 and return 404. \`/graphql\`
is intentionally unversioned and POST-only.

## GraphQL

| query | permission | notes |
| --- | --- | --- |
| viewer | authenticated member | safe account + active membership |
| organization | organization.read | active organization summary |
| organizationMembers(first, after) | members.read | bounded connection |
| organizationInvitations(first, after) | invitations.read | metadata only, no raw tokens |
| organizationAuditEvents(first, after) | audit.read | bounded event metadata |
| regions(first, after) | authenticated member | global public region connection |
| region(slug) | authenticated member | one global public region |

The schema has no mutation or subscription root in Phase 4.
`;
}

void main();
