import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // `components/ui/` and `hooks/use-mobile.ts` are GENERATED by
  // `npx shadcn@latest add`, and both trip `react-hooks/set-state-in-effect`
  // (docs/design-system.md §11). They are not patched, because the CLI
  // overwrites them on the next `add` — a local fix would be reverted silently,
  // turning a visible lint error into an invisible one. The rule is turned off
  // for exactly those paths and nowhere else; our own code in `components/acres/`
  // is still held to it. See docs/components.md §6.
  {
    files: ["components/ui/**", "hooks/use-mobile.ts"],
    rules: {
      "react-hooks/set-state-in-effect": "off",
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
  ]),
]);

export default eslintConfig;
